apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-von-network
  labels:
    app: von-network
spec:
  selector:
    app: von-network
  ports:
    - name: web
      port: 9000
      targetPort: {{ .Values.webserver.port }}
---
{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-von-data
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
---
{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-von-network
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: von-network
{{- end }}
